### ISSUE TITLE
500 error on specific pin, and More Details button not working from list.

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#112]
https://yourpeer.nyc/locations/services-now-for-adult-persons-snap produces a server error (500)
https://gogetta.nyc/team/location/5465bc20-996d-4ec3-a8b8-363a6c0a5787

**Comment by adambard1** [comment]
Much more importantly, Safe Horizon Streetwork - one of our most in-demand locations also has this same error. Pls fix as an urgent prio pls @jbeard4 
https://yourpeer.nyc/locations/safe-horizon-streetwork-project-harlem
https://gogetta.nyc/team/location/29301fb5-020f-473d-9cff-70584edad23c
Another part of the bug, presumably linked, is that the "More details" button on list for the service doesn't do anything.

**Comment by jbeard4** [comment]
Hi sorry I missed this before. I will look at this today

**Comment by adambard1** [comment]
Did the commit get deployed? The issue is still happening.
