### ISSUE TITLE
Age requirement text format

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#142]
For the Age requirement information the format/logic for the age range information should be, using the info on the sheet:

"Age requirement: [Age min]-[Age max] (until your [Age max+1][suffix] birthday)"

The age max is always an inclusive number. I would prefer that we didn't show any ages that can't access the service, which is why we want to use inclusive numebr sin the age range, but the age range is so often misused by organizations by including the year older than can access the service, that the clarification has always been helpful.

**Comment by adambard1** [comment]
Thanks, Jake Are you able to do a refresh on the ages? AFC maximum age is 1 year high - I know doobneek had all their upper bounds too high, but they edited them last week.

<img width="1068" alt="Screenshot 2024-06-20 at 9 22 36 AM" src="https://github.com/streetlives/yourpeer.nyc/assets/13530245/98e42486-8dd6-4406-a37d-bc091d7b2d73">
<img width="404" alt="Screenshot 2024-06-20 at 9 24 36 AM" src="https://github.com/streetlives/yourpeer.nyc/assets/13530245/c7123e30-7df1-474a-9d3e-52b0a502386a">

**Comment by jbeard4** [comment]
Fixed
![image](https://github.com/streetlives/yourpeer.nyc/assets/586962/6a7a859c-0a49-4497-835d-1649b668f680)

**Comment by jbeard4** [comment]
Fixed in a7479293c82707c19ebdc91686772210f7e1c160

**Comment by jbeard4** [comment]
@adambard1 This is ready for re-review
