### ISSUE TITLE
Have the map load centered on the user location, if a user has enabled their location

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#15]
It's a disorienting desktop user experience to always have the map load by panning to Central Park and then to my location.

It's a much better experience on mobile (assuming you don't immediately jump to the map), as it appears as if the map has loaded to my location (as it was loading 'behind' the list).

- [ ] If I have enabled my location on desktop, have the map load at my location without it centering on Central park first

https://github.com/streetlives/streetlives_v2/assets/13530245/805eed65-0ca9-41ef-87fd-a30d7f322b4c

https://github.com/streetlives/streetlives_v2/assets/13530245/d6ebb3cf-3460-4f91-99fa-65399efb92cb

Even better is that the map doesn't zoom out following manual zoom, so subsequent map loads are a friendly UX. The first load should be that friendly.

https://github.com/streetlives/streetlives_v2/assets/13530245/fb933e18-729d-43b9-82d7-e600a5787cd5

**Comment by adambard1** [comment]
> [x] If I have enabled my location on desktop, have the map load at my location without it centering on Central park first

This doesn't appear to be happening when first loading, or any time I've gone back to the homepage, or when I "clear filters" though it is happening when e.g., I switch filter categories or pills.

https://github.com/streetlives/yourpeer.nyc/assets/13530245/769997ee-c64f-40df-ae55-310bdabb6327

**Comment by adambard1** [comment]
Asynchronous operation.
Map resolves before user's location is discovered

**Comment by adambard1** [comment]
Can we have a nice loading animation until the location is either found or it centers on Central Park

**Comment by shakilhossain1** [comment]
I added a loading animation to this.
