### ISSUE TITLE
Nextjs refactor: Show bullet symbol in list view

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#175]
Lists are not displaying bullets in the service detail field, e.g. Maimonedes Sunset Park ([heroku](https://yourpeer-f5f080230d56.herokuapp.com/locations/maimonides-health-sunset-park)) ([Gogetta service field](https://gogetta.nyc/team/location/c79fbcf4-edb2-4252-a06f-7dead52a26ef/services/07605a57-ee50-49c2-9795-831665b18e66/description))
<img width="352" alt="Screenshot 2024-07-17 at 09 07 04" src="https://github.com/user-attachments/assets/796bf432-815f-4da3-a534-959eaab08e18">
<img width="474" alt="Screenshot 2024-07-17 at 09 00 45" src="https://github.com/user-attachments/assets/791fe969-507b-418e-8f9b-bf3a6fe65408">

**Comment by jbeard4** [comment]
Confirmed fixed in https://github.com/streetlives/yourpeer.nyc-nextjs/pull/18
