### ISSUE TITLE
Nextjs refactor: Remove the zoom controls from the mini map on the mobile location details page

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#178]
We don't need these controls in this view, as they are obscured by the 'View Street View' button.
<img width="344" alt="Screenshot 2024-07-17 at 09 26 09" src="https://github.com/user-attachments/assets/49536844-fe6c-4424-875d-2aabde4d106c">

**Comment by jbeard4** [comment]
Confirmed fixed in https://github.com/streetlives/yourpeer.nyc-nextjs/pull/18
