### ISSUE TITLE
Look at our response codes handling

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#2]
"One thing of concern I am noticing is that all of these [URLs mentioned in streetlives/yourpeer.nyc-nextjs#96] should be serving a 404 response code, not a 401 as you mention or a 301 redirect to a 200 response code page like I'm seeing.
Can we look at the systems that are serving our response codes for pages that aren't found on the server? The server behavior isn't as expected and I'm having a hard time diagnosing what is happening.

When the server is asked for a URL that it doesn't recognize, the appropriate response is to return an HTTP response header of 404 (along with a custom page that directs the user). It is important that the response code is a 404 (not a 200 or anything else). This URL, from your list, is behaving very strangely.

https://yourpeer.nyc/locations/acacia-network-bronx-e-e 

There's a 301 redirect, but I'm not sure where that is coming from because it is not in the response header. Another method is being used. Then, the user lands on a page that looks like a system default 404 response but is actually served with a 200 response code. I'm seeing a different set of behavior for this URL in the crawler vs a browser.

I'm less concerned about redirecting these 700~ URLs because they never had value but it wouldn't harm anything to clean them up with redirects where appropriate. I am concerned about our response code handling. Can we dive into this matter?

**Comment by jbeard4** [comment]
Unable to reproduce. Followed up with Lindsay for instructions on how to reproduce.
