### ISSUE TITLE
The back button from the details view it should go to the view that we came from

### ISSUE THREAD

**Issue by mixedpaper** [streetlives/yourpeer.nyc-django#79]
On mobile, when you look at the location detail page having selected "See more details" from the Map tray, you should go back to the tray.

**Comment by micahasmith** [comment]
pinged @shakilhossain1 on slack for more info on where this click occurs in code. then i can look into it

**Comment by micahasmith** [comment]
ready on test

**Comment by adambard1** [comment]
see issue streetlives/streetlives_v2#392 for the steps to recreate issue on back button clearing the filter view

**Comment by adambard1** [comment]
If you are on the map and go to a location details page (on mobile) then click the internal back buttonl you should go back to the map. Currently we are always taken to the list. This is sort of OK, bvut clearing the category filter is not so let's fix streetlives/streetlives_v2#392 for launch

**Comment by micahasmith** [comment]
is this a dupe of streetlives/streetlives_v2#392?
