### ISSUE TITLE
Don't show 'None' if there is no location name, just collapse the line

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#8]
Locations without a location name––they will usually only have location names to distinguish locations where the Organization has more than one location––should not (and previously never did) have the word 'None' in the location name field.

- [x] When there is no location name, don't show the location name line.

e.g., 
<img width="537" alt="Screenshot 2024-04-26 at 10 03 37" src="https://github.com/streetlives/streetlives_v2/assets/13530245/c0b345a8-6701-4599-9800-22c9c81fb1a0">

**Comment by adambard1** [comment]
has this gone to Test @jbeard4 - None still shows for the location name on test atm

**Comment by jbeard4** [comment]
No, let me deploy it

**Comment by adambard1** [comment]
This is fixed

**Comment by adambard1** [comment]
re-opening since it hasn't been code reviewed. Didn't know closing it would move it automatically to 'Done'
