### ISSUE TITLE
Mobile Search UI not the same as live site

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc-django#85]
Clicking into the search bar should produce the Search page as on the live site
Search works, but requires the -> button to be pushed on the keypad

**Comment by micahasmith** [comment]
i'll take this one

**Comment by micahasmith** [comment]
fixed on local

**Comment by micahasmith** [comment]
fixed on test

**Comment by adambard1** [comment]
Fixed on desktop, not on mobile.
Entering a term leads to Server Error (500) which I've posted in streetlives/streetlives_v2#353 

Live moble UI is:
<img width="405" alt="Screenshot 2024-02-15 at 10 47 21" src="https://github.com/streetlives/streetlives_v2/assets/13530245/e66b4f59-bd98-473e-948c-5e411634cf9a">
